import { z } from 'zod';

import { RequestIdSchema } from './primitives.js';

/**
 * Stable codes are part of the public integration contract. User-facing text
 * may change, but callers must make decisions from these values only.
 */
export const ReasonCodeSchema = z.enum([
  'AUTHORIZED',
  'APPROVAL_REQUIRED',
  'HUMAN_APPROVAL_REQUIRED',
  'AMOUNT_EXCEEDED',
  'AMOUNT_OUT_OF_RANGE',
  'BUDGET_EXCEEDED',
  'CURRENCY_NOT_ALLOWED',
  'FORBIDDEN_CATEGORY',
  'NEW_CATEGORY',
  'LOW_TRUST_MERCHANT',
  'UNMAPPED_CATEGORY',
  'MISSING_MANDATE',
  'MANDATE_NOT_FOUND',
  'MANDATE_INACTIVE',
  'MANDATE_PAUSED',
  'MANDATE_REVOKED',
  'MANDATE_EXPIRED',
  'AGENT_MISMATCH',
  'AGENT_AUTH_REQUIRED',
  'AGENT_PROOF_INVALID',
  'AGENT_KEY_REVOKED',
  'MERCHANT_MISMATCH',
  'MERCHANT_AUTH_REQUIRED',
  'MERCHANT_INACTIVE',
  'MERCHANT_NOT_REGISTERED',
  'MERCHANT_ENDPOINT_MISMATCH',
  'QUOTE_NOT_FOUND',
  'QUOTE_EXPIRED',
  'QUOTE_MERCHANT_MISMATCH',
  'QUOTE_SIGNATURE_INVALID',
  'QUOTE_KEY_UNKNOWN',
  'CART_CHANGED',
  'ORDER_QUOTE_MISMATCH',
  'ORDER_REFERENCE_CONFLICT',
  'ORDER_ALREADY_VERIFIED',
  'VERIFICATION_IN_PROGRESS',
  'CAPABILITY_INVALID',
  'CAPABILITY_EXPIRED',
  'CAPABILITY_REPLAYED',
  'CAPABILITY_CLAIMED',
  'CAPABILITY_REVOKED',
  'APPROVAL_EXPIRED',
  'APPROVAL_DENIED',
  'PAYMENT_METHOD_DISABLED',
  'PAYMENT_AUTHORIZATION_DECLINED',
  'PAYMENT_AUTHORIZATION_TIMEOUT',
  'PAYMENT_CAPTURE_FAILED',
  'PAYMENT_PENDING',
  'PAYMENT_RECONCILIATION_REQUIRED',
  'PAYMENT_OPERATION_NOT_FOUND',
  'IDEMPOTENCY_KEY_REQUIRED',
  'IDEMPOTENCY_KEY_REUSED',
  'ACTOR_NOT_ALLOWED',
  'REQUEST_PROOF_EXPIRED',
  'REQUEST_REPLAYED',
  'NONCE_REQUIRED',
  'INVALID_REQUEST',
  'MALFORMED_REQUEST',
  'CONTENT_TYPE_REQUIRED',
  'REQUEST_TOO_LARGE',
  'RATE_LIMITED',
  'RATE_LIMIT_UNAVAILABLE',
  'INSUFFICIENT_INVENTORY',
  'SKU_NOT_FOUND',
  'MANDATE_VERIFICATION_UNAVAILABLE',
  'SERVICE_UNAVAILABLE',
  'INTERNAL_ERROR',
  'ROUTE_NOT_FOUND',
  'DEMO_SCENARIO_FORBIDDEN',
  'DEMO_SCENARIO_UNKNOWN',
]);

export const ApiErrorSchema = z
  .object({
    error: z
      .object({
        code: ReasonCodeSchema,
        message: z.string().min(1).max(1_024),
        requestId: RequestIdSchema,
      })
      .strict(),
  })
  .strict();

export type ReasonCode = z.infer<typeof ReasonCodeSchema>;
export type ApiError = z.infer<typeof ApiErrorSchema>;
